services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db5785
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: username@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pgnetwork

  python:
    image: python:latest
    volumes:
      - ./your-python-scripts:/app
    working_dir: /app
  #  command: python activities.py
    networks:
      - pgnetwork
    depends_on:
      - db

volumes:
  postgres_data:
    external: false

networks:
  pgnetwork:
